# Generated by Django 3.1 on 2020-08-20 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_business_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
