# Generated by Django 3.1 on 2020-08-21 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hood',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='application.neighbourhood'),
        ),
    ]
