# Generated by Django 3.1 on 2020-08-21 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20200821_1232'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
